name: QA

on:
  pull_request:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "**/*.md"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Typecheck
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
